#!/usr/bin/env bash

# Name this file something like run_concat.sh and make it executable:
# chmod +x run_concat.sh

# 1. Define the array of files
files=(
"README.md"
"bin/domain-definitions-summary.md"
"bin/domain-tasks.md"
"bin/metrics.md"
"commander-output/2024-12-20-commander-output.md"
"data/2024-12-19 folders.md"
"data/transcripts/2024-11/2024-11-15-transcript.md"
"data/transcripts/2024-11/2024-11-21-transcript.md"
"data/transcripts/2024-11/2024-11-28 model context protocol integration.md"
"data/transcripts/2024-12/2024-12-02 autonomous ai agents on blockchain/2024-12-02-autonomous-ai-agents-on-blockchain.md"
"data/transcripts/2024-12/2024-12-02 autonomous ai agents on blockchain/SUMMARY.md"
"data/transcripts/2024-12/2024-12-03 chat ui definitions reasoning.03/2024-12-03 chat ui definitions reasoning.03.txt"
"data/transcripts/2024-12/2024-12-03 chat ui definitions reasoning.03/SUMMARY.md"
"data/transcripts/2024-12/2024-12-03.01 autonomous ai agent definitions/2024-12-03.01 autonomous ai agent definitions.txt"
"data/transcripts/2024-12/2024-12-03.01 autonomous ai agent definitions/SUMMARY.md"
"data/transcripts/2024-12/2024-12-03.02 decentralized ai platform definitions/2024-12-03.02 decentralized ai platform definitions.txt"
"data/transcripts/2024-12/2024-12-03.02 decentralized ai platform definitions/SUMMARY.md"
"data/transcripts/2024-12/2024-12-03.03-chat-ui-definitions-reasoning/2024-12-03.03-chat-ui-definitions-reasoning.md"
"data/transcripts/2024-12/2024-12-03.03-chat-ui-definitions-reasoning/SUMMARY.md"
"data/transcripts/2024-12/2024-12-04 reasoning domains and interfaces between them/2024-12-04 reasoning domains and interfaces between them.txt"
"data/transcripts/2024-12/2024-12-04 reasoning domains and interfaces between them/SUMMARY.md"
"data/transcripts/2024-12/2024-12-08 o1 pro for reasoning/2024-12-08 o1 pro for reasoning.txt"
"data/transcripts/2024-12/2024-12-08 o1 pro for reasoning/SUMMARY.md"
"data/transcripts/2024-12/2024-12-09 code as renders/2024-12-09 code as renders - reasoning about making modules.txt"
"data/transcripts/2024-12/2024-12-09 code as renders/SUMMARY.md"
"data/transcripts/2024-12/2024-12-09 the economic model of the dreamcatcher/2024-12-09 the economic model of the dreamcatcher.txt"
"data/transcripts/2024-12/2024-12-09 the economic model of the dreamcatcher/SUMMARY.md"
"data/transcripts/2024-12/2024-12-10 o1 pro concat tool to include folders/2024-12-10 o1 pro concat tool to include folders.txt"
"data/transcripts/2024-12/2024-12-10 o1 pro concat tool to include folders/SUMMARY.md"
"data/transcripts/2024-12/2024-12-11_whatsapp_BH-TT_artifact-differences/2024-12-11_whatsapp_BH-TT_artifact-differences.txt"
"data/transcripts/2024-12/2024-12-11_whatsapp_BH-TT_artifact-differences/README.md"
"data/transcripts/2024-12/2024-12-11_whatsapp_BH-TT_artifact-differences/SUMMARY.md"
"data/transcripts/2024-12/2024-12-12 o1-pro reasons about a pure git blockchain/2024-12-12 o1-pro reasons about a pure git blockchain.m4a.txt"
"data/transcripts/2024-12/2024-12-12 o1-pro reasons about a pure git blockchain/SUMMARY.md"
"data/transcripts/2024-12/2024-12-12-whatsapp_SM-TT_stuff/2024-12-12-whatsapp_SM-TT_stuff.txt"
"data/transcripts/2024-12/2024-12-14 o1-pro as project overlord/2024-12-14 o1-pro as project overlord.m4a.txt"
"data/transcripts/2024-12/2024-12-14 o1-pro as project overlord/SUMMARY.md"
"data/transcripts/2024-12/2024-12-16-making-Command-be-dreamcatcher-native/2024-12-16-making-Command-be-dreamcatcher-native.md"
"data/transcripts/2024-12/2024-12-16-making-Command-be-dreamcatcher-native/SUMMARY.md"
"data/transcripts/2024-12/2024-12-18 what value is software if o1-pro can do it for pennies/2024-12-18 what value is software if o1-pro can do it for pennies.md"
"data/transcripts/2024-12/2024-12-18 what value is software if o1-pro can do it for pennies/SUMMARY.md"
"data/transcripts/2024-12/2024-12-20 project management first stucks review/SUMMARY.md"
"data/transcripts/2024-12/2024-12-20 project management first stucks review/condensed.md"
"data/transcripts/2024-12/2024-12-20 project management first stucks review/raw.md"
"data/transcripts/2024-12/2024-12-22 saw sharpening: commander architecture, transcriptions tooling, git usage/raw.md"
"deno.json"
"dependency_graph.svg"
"discussion-topics.md"
"domains/Interfaces/Interface-domain-Dreamcatcher-domain-DC.md"
"domains/README.md"
"domains/commander/README.md"
"domains/commander/commander.md"
"domains/commander/directive.md"
"domains/commander/implied-stuck.md"
"domains/decentralized-ai/README.md"
"domains/decentralized-ai/agent-resource-acquisition.md"
"domains/decentralized-ai/ai-native-blockchain.md"
"domains/decentralized-ai/censorship-resistance.md"
"domains/decentralized-ai/consensus-mechanism.md"
"domains/decentralized-ai/decentralized-AI-Agent.md"
"domains/decentralized-ai/decentralized-computation-marketplace.md"
"domains/decentralized-ai/decentralized-income.md"
"domains/decentralized-ai/dreamcatcher-platform.md"
"domains/decentralized-ai/howey-test.md"
"domains/decentralized-ai/negotiation-and-bargaining.md"
"domains/decentralized-ai/proof-of-inference.md"
"domains/decentralized-ai/regulatory-compliance.md"
"domains/decentralized-ai/trustlessness.md"
"domains/decentralized-ai/unstoppable-agents.md"
"domains/decentralized-ai/value-distribution-mechanism.md"
"domains/decentralized-ai/value-exchange.md"
"domains/generic-crm-test/README.md"
"domains/generic-crm-test/communication-logging.md"
"domains/generic-crm-test/community-building.md"
"domains/generic-crm-test/community-engagement.md"
"domains/generic-crm-test/contract-management.md"
"domains/generic-crm-test/customer-management.md"
"domains/generic-crm-test/customer-tasks-and-reminders.md"
"domains/generic-crm-test/incident-control-and-resolution.md"
"domains/generic-crm-test/incident-handling.md"
"domains/generic-crm-test/internal-metrics-and-logging.md"
"domains/generic-crm-test/lead-journey.md"
"domains/generic-crm-test/lead-management.md"
"domains/generic-crm-test/marketing-strategy.md"
"domains/generic-crm-test/marketing.md"
"domains/generic-crm-test/privacy-and-access-control.md"
"domains/generic-crm-test/recruitment-and-talents.md"
"domains/generic-crm-test/time-and-cost-logging.md"
"domains/innovation/README.md"
"domains/innovation/actor-consumer.md"
"domains/innovation/actor-demander.md"
"domains/innovation/actor-funder.md"
"domains/innovation/actor-service-provider.md"
"domains/innovation/actor-talent.md"
"domains/innovation/actor-trader.md"
"domains/innovation/actor.md"
"domains/innovation/ai-agent.md"
"domains/innovation/alpha-network.md"
"domains/innovation/ambient-attribution.md"
"domains/innovation/artifact.md"
"domains/innovation/asset.md"
"domains/innovation/attribution-algorithm.md"
"domains/innovation/beta-network.md"
"domains/innovation/consensus-mode.md"
"domains/innovation/contribution.md"
"domains/innovation/contributor.md"
"domains/innovation/decentralized-income.md"
"domains/innovation/definition.md"
"domains/innovation/direct-stuck.md"
"domains/innovation/dreamcatcher-foundation.md"
"domains/innovation/dreamcatcher-platform.md"
"domains/innovation/estimation-tool.md"
"domains/innovation/gateway-network.md"
"domains/innovation/homebrew-platform.md"
"domains/innovation/hosting.md"
"domains/innovation/identity-verification.md"
"domains/innovation/identity.md"
"domains/innovation/impact-crystal.md"
"domains/innovation/implied-stuck.md"
"domains/innovation/interaction-story.md"
"domains/innovation/intrinsic-currency.md"
"domains/innovation/issuer.md"
"domains/innovation/jita.md"
"domains/innovation/kyc.md"
"domains/innovation/legal-entity.md"
"domains/innovation/legal-gateway-relationships.md"
"domains/innovation/legal-gateway.md"
"domains/innovation/napp-discovery.md"
"domains/innovation/napp.md"
"domains/innovation/payment-path.md"
"domains/innovation/platform-instance.md"
"domains/innovation/platform.md"
"domains/innovation/protocol.md"
"domains/innovation/qa.md"
"domains/innovation/regulatory-compliance.md"
"domains/innovation/shockwave.md"
"domains/innovation/stuck-loop-process.md"
"domains/innovation/stuck-template.md"
"domains/innovation/stuck.md"
"domains/innovation/trading-as.md"
"domains/innovation/universal-api-gateway.md"
"domains/innovation/user-story.md"
"domains/innovation/value-exchange.md"
"domains/reasoning/README.md"
"domains/reasoning/coherence.md"
"domains/reasoning/consistency.md"
"domains/reasoning/correctness.md"
"domains/reasoning/domain-rules.md"
"domains/reasoning/domain.md"
"domains/ui/README.md"
"domains/ui/diagram-rules.md"
"domains/ui/web-app.md"
"inventor-notebook/README.md"
"inventor-notebook/ideas/README.md"
"inventor-notebook/ideas/economic-formulas.md"
"inventor-notebook/ideas/economic-model-framework.md"
"inventor-notebook/ideas/multi-actor-value-optimization.md"
"inventor-notebook/ideas/napp-scenarios.md"
"inventor-notebook/ideas/narratives.md"
"inventor-notebook/ideas/project-management-napp.md"
"inventor-notebook/ideas/red-team-arguments.md"
"inventor-notebook/raw/2024-11-14-definitions.md"
"inventor-notebook/raw/2024-11-14-tasks.md"
"inventor-notebook/raw/2024-11-14-transcript.md"
"inventor-notebook/raw/2024-11-15-definitions.md"
"inventor-notebook/raw/2024-11-15-narratives.md"
"inventor-notebook/raw/2024-11-15-tasks.md"
"inventor-notebook/raw/2024-11-20-notes.md"
"inventor-notebook/raw/external/2024-08-23 Explainability and Interpretability"
"inventor-notebook/raw/real-world/2024-11-28 James Browning.m4a.txt"
"inventor-notebook/raw/scott/proposed-by-others.md"
"inventor-notebook/raw/scott/raw-notes.md"
"inventor-notebook/raw/tom/proposed-by-others.md"
"inventor-notebook/raw/tom/raw-notes.md"
"napps/2024-12--14-diarise-transcripts/Napp-diarise-transcripts.md"
"napps/2024-12-14 Summarise-transcripts/Napp-Summarise-transcripts.md"
"napps/2024-12-15-Commander/Napp-Commander.md"
"napps/2024-12-15-Commander/README.md"
"napps/2024-12-17-brief-the-commander/brief-the-commander.sh"
"plan/commander-plan.md"
"progress-reports/README.md"
"progress-reports/scott/2024-11/2024-11-29-REPORT-SM-folder structure and stuck loop.md"
"progress-reports/scott/2024-11/2024-11-SM-Tasks.md"
"progress-reports/scott/2024-11/2024-12-02 DCI initial rough cut.md"
"progress-reports/scott/2024-11/2024-12-03 Expantion of Decentralised AI"
"progress-reports/scott/2024-11/2024-12-18-SM-commander-use-and-folder-update/2024-12-18-SM-commander-use-and-folder-update"
"stucks/2024-12-11 Reasoning between commits/2024-12-11 Reasoning between commits."
"stucks/README.md"
"stucks/S1-Git-Based Artifact Database.md"
"stucks/S10-Stuck & Solution Search Widget.md"
"stucks/S11-Multi-User Shared Artifact Repos.md"
"stucks/S12-Multi-Repo User Support.md"
"stucks/S13-Local-to-Cloud NApp Sync.md"
"stucks/S14-Stuck Graph Visualization.md"
"stucks/S15-Interactive Stucks Management Agent.md"
"stucks/S16-Formal Stucks Schema.md"
"stucks/S17-Plain-Text NApp-to-NApp Calls.md"
"stucks/S18-NApp CLI Tool.md"
"stucks/S19-Automated O1 Code Generation.md"
"stucks/S2-XML Data Sync (MoneyWorks → Artifact).md"
"stucks/S20-OpenAI NApp Integration.md"
"stucks/S21-Auto-Commander Updates on Commits.md"
"stucks/S22-Enhanced PR Workflow for NApps Repo.md"
"stucks/S23-UI-Based Billing Integration.md"
"stucks/S24-Deliver the Trucking App.md"
"stucks/S25-Develop Commander AI for Complexity Management.md"
"stucks/S26-Establish Knowledge Structures and Mapping for Commander.md"
"stucks/S27-Implement Robust Task (\"Stuck\") Structure with Estimates and Retrospectives.md"
"stucks/S28-Unify Code and Knowledge Repositories.md"
"stucks/S29-Deploy and Integrate \"Concat\" Tool.md"
"stucks/S3-Standard Widget-Ready UI.md"
"stucks/S30-Deploy O1 Pro as Commander AI.md"
"stucks/S31-Allocate Resources Based on Value Units.md"
"stucks/S32-Map Tasks, Dependencies, and Risks.md"
"stucks/S33-Define and Assign \"Stucks\" as Tasks.md"
"stucks/S34-Develop Module Mapping System.md"
"stucks/S35-Ensure Regulatory Compliance.md"
"stucks/S36-Prioritize and Deliver the Trucking App Using AI Capabilities.md"
"stucks/S37-Reevaluate M&A and Strategic Opportunities Post-Stabilization.md"
"stucks/S38-Implement Quality Assurance (QA) Processes to Control Complexity and Costs.md"
"stucks/S39-Continuously Record Work, Measure Outcomes, and Maintain Strategic Flexibility.md"
"stucks/S39-continuously-record-work-measure-outcomes-and-maintain-strategic-flexibility.md"
"stucks/S4-Customer Live Search Widget.md"
"stucks/S40 - implement-gantt-chart-generation.md"
"stucks/S41 - domain-interface-summary-aggregator.md"
"stucks/S42 - establish-monthly-commanders-report-napp.md"
"stucks/S43 - Commit-reasoning-napp.md"
"stucks/S5-Privy-Based User Authentication.md"
"stucks/S6-Web-to-Artifact Auth Bridge.md"
"stucks/S7-Filesystem-Based NApp Execution.md"
"stucks/S8-Standard NApp Format Definition.md"
"stucks/S9-Artifact-Based NApp Execution.md"
"stucks/priority-list.md"
"this-repo-evals/corrections.md"
)

# 2. Make (or clear) an output file
> output.txt

# 3. Loop through each file
for file in "${files[@]}"; do
  echo "Running concat on: $file"
  
  # Capture the output of concat
  concat_output=$(concat "$file" 2>&1)
  
  # The concat output is expected to contain a line like:
  # "Operation complete! created concat.txt with XXX o1 token"
  # We'll grep for the number (XXX)
  token_count=$(echo "$concat_output" | grep -oE 'with[[:space:]]+[0-9]+[[:space:]]+o1 token' | grep -oE '[0-9]+')
  
  # If we found the token count, write "<filename> <count>" to output.txt
  if [[ -n "$token_count" ]]; then
    echo "$file $token_count" >> output.txt
  else
    # If we didn't find it, maybe log an error or mark it
    echo "$file ERROR_NO_TOKEN_FOUND" >> output.txt
  fi
done

echo "Done! Check output.txt for results."

